### ISSUE TITLE
Regripper4.0 plugin "eventsasp.pl" is missing a Short Description

### ISSUE THREAD

**Issue by CmdrBurrito** [keydet89/RegRipper4.0#4]
FYI, the Regripper 4.0 plugin named "eventsasp.pl" is missing a Short Description.

sub getShortDescr {
	return "";
}

That is to say, the return value of its "getShortDescr" subroutine is currently blank.  Instead, it should probably return something along the lines of, "Get the SOFTWARE hive keys associated with the Event Viewer Online Help system" (or similar).

**Comment by keydet89** [comment]
I'm really unclear how that impacts the function of the plugin.

Are you doing all of this because you're looking at incorporating the tool into your own product?

**Comment by CmdrBurrito** [comment]
Hi Harlan,

Nope, no ulterior motive here, not looking to incorporate the tool into another product or anything.  I'm just an (overly enthusiastic?) fan of this excellent software utility that I use on a regular basis.

As mentioned, this particular issue does not affect the actual function of the plugin.  I just noticed it as a very minor missing thing (which I have corrected on my own system), and thought I'd report it up the chain so that it can be fixed for future posterity.  Perhaps I shouldn't have used this forum to report such a small and unimportant, oversight?

If this is the wrong forum to report such things, or if this is turning out to be more of an annoyance rather than a help, I will refrain from pointing out any similar small defects like this in the future.  My sincerest apologies.

**Comment by keydet89** [comment]
No, this isn't the wrong forum.

The "issue", if you want to call it that, is that I keep getting messages about small fixes that don't impact that function of plugins, nor of the overall tool, at all. My email address is in the header of every plugin, and these little things keep getting posted here.

Not issues that affect the performance of the tool. 

Not, "...hey, using RegRipper I found a new thing...here's a hive, can you write a plugin for it..."?

Not, "...hey, running Yara through RegRipper is way cool, how do you make it do X?"

The fact that a plugin is missing short description or a MITRE ATT&CK mapping doesn't impact the function or use of the tool.

Thanks for your enthusiasm, though! I do appreciate that.

**Comment by CmdrBurrito** [comment]
Roger that!  In that case, I'll reserve reports on this website to any functional issues that I may discover.  

From now on I'll keep any reports regarding things that do not affect functionality, either to myself, or send you a quick note via email.  Again, my apologies for any annoyance I may have caused.

**Comment by keydet89** [comment]
No annoyance has been caused.
